/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.opentracing.contrib.annotation;

import io.opentracing.mock.MockSpan;
import io.opentracing.mock.MockTracer;
import io.opentracing.util.GlobalTracer;
import org.junit.After;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.runners.MockitoJUnitRunner;

import javax.jms.Message;
import java.util.Date;
import java.util.List;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.assertThat;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class PeformanceTest {

    @Mock private Message message;

    @Test
    public void testWithNoArgs() {
        long start = new Date().getTime();

        for (int i = 0; i < 1000; i++) {
            new ClassWithNewSpanAnnotation().withEmptyArgs();
        }

        long end = new Date().getTime();
        System.out.println("total time taken testWithNoArgs :: " + ((end - start) / 1000.0) + " ms");

    }

    @Test
    public void testWithSpanArgs() {
        long start = new Date().getTime();

        for (int i = 0; i < 1000; i++) {
            new ClassWithNewSpanAnnotation().withSpanArgs(null);
        }

        long end = new Date().getTime();
        System.out.println("total time taken testWithSpanArgs :: " + ((end - start) / 1000.0) + " ms");
    }


    @Test
    public void testWithSpanArgsOnExtraLogic() {
        long start = new Date().getTime();

        for (int i = 0; i < 1000; i++) {
            new ClassWithNewSpanAnnotation().withExtraLogicOnSpanArgs(null);
        }

        long end = new Date().getTime();
        System.out.println("total time taken withExtraLogicOnSpanArgs :: " + ((end - start) / 1000.0) + " ms");
    }

    @Test
    public void testNewSpanCreation() {
        long start = new Date().getTime();

        for (int i = 0; i < 1000; i++) {
            new ClassWithNewSpanAnnotation().withEmptyArgs();
        }

        long end = new Date().getTime();
        System.out.println("total time taken testNewSpanCreation :: " + ((end - start) / 1000.0) + " ms");

    }

    @Test
    public void testNewSpanCreationWithOverrideOperationName() {
        long start = new Date().getTime();

        for (int i = 0; i < 1000; i++) {
            new ClassWithNewSpanAnnotation().withOperationName();
        }

        long end = new Date().getTime();
        System.out.println("total time taken testNewSpanCreation :: " + ((end - start) / 1000.0) + " ms");

    }

    @Test
    public void testNewSpanCreationWithTag() {
        long start = new Date().getTime();

        for (int i = 0; i < 1000; i++) {
            new ClassWithNewSpanAnnotation().withTag("tag-value");
        }

        long end = new Date().getTime();
        System.out.println("total time taken testNewSpanCreationWithTag :: " + ((end - start) / 1000.0) + " ms");

    }

    @Test
    public void testNewSpanCreationWithAdvanceTag() throws Exception {

        // Given
        when(message.getJMSMessageID()).thenReturn("msg-id-sample");

        long start = new Date().getTime();

        for (int i = 0; i < 1000; i++) {
            new ClassWithNewSpanAnnotation().withAdvanceTag(message);
        }

        long end = new Date().getTime();
        System.out.println("total time taken testNewSpanCreationWithAdvanceTag :: " + ((end - start) / 1000.0) + " ms");

    }

    @Test
    public void testNewSpanCreationWithAdvanceTagArgumentNotMatch() throws Exception {
        // Given
        long start = new Date().getTime();
        for (int i = 0; i < 1000; i++) {
            // When
            new ClassWithNewSpanAnnotation().withAdvanceTagNotMatchedArgument("tony");
        }

        long end = new Date().getTime();
        System.out.println("total time taken testNewSpanCreationWithAdvanceTagArgumentNotMatch :: " + ((end - start) / 1000.0) + " ms");

    }

    @Test
    public void testNewSpanCreationWithInternalMethodCalled() {
        long start = new Date().getTime();

        for (int i = 0; i < 1000; i++) {
            // When
            new ClassWithNewSpanAnnotation().internalMethodCallwithTag();
        }

        long end = new Date().getTime();
        System.out.println("total time taken testNewSpanCreationWithInternalMethodCalled :: " + ((end - start) / 1000.0) + " ms");

    }

    @Test
    public void testNewSpanCreationWithUnsupportedValueTag() {
        long start = new Date().getTime();

        for (int i = 0; i < 1000; i++) {
            // When
            new ClassWithNewSpanAnnotation().withUnsupportedValueTag("tony".getBytes());
        }

        long end = new Date().getTime();
        System.out.println("total time taken testNewSpanCreationWithUnsupportedValueTag :: " + ((end - start) / 1000.0) + " ms");

    }
}
