/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.opentracing.contrib.annotation

import kotlin.test.Test


class LibraryTest {

    @Test
    fun sometest() {
        val testClass = ClassWithNewSpanAnnotation()
        testClass.performSomeLogic()
    }

}
