/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.opentracing.contrib.annotation

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
