/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.opentracing.contrib;

import io.opentracing.Span;
import io.opentracing.Tracer;
import io.opentracing.util.GlobalTracer;
import org.junit.Test;

public class LibraryTest {
    @Test
    public void testAnnote() {
        Span span = null;

        ClassWithNewSpanAnnotation classWithNewSpanAnnotation = new ClassWithNewSpanAnnotation();
        classWithNewSpanAnnotation.performSomeLogic(span);

        System.out.println("span :: " + span);
//        Tracer tracer = GlobalTracer.get();
//        tracer.scopeManager().
    }
}
