/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.opentracing.contrib;

import org.junit.Test;

public class LibraryTest {
    @Test
    public void testAnnote() {
        ClassWithNewSpanAnnotation classWithNewSpanAnnotation = new ClassWithNewSpanAnnotation();
        classWithNewSpanAnnotation.performSomeLogic();

    }
}
